### ISSUE TITLE
Allow specifying individual repos

### ISSUE THREAD

**Issue by jayvdb** [orf/git-workspace#171]
While it is very useful to manage all repos in an org together, most of my orgs have too many repos, including many I am not interested in.

It would be nice if individual repos can be supported.

**Comment by orf** [comment]
The idea behind this tool is that disk space is cheap, and you may indeed want to switch between repos you're not _currently_ interested in at a future point in time. I've got about 1085 repos cloned locally from my org, using relatively little space when compared to something like my Docker daemon.

What kind of interface are you thinking for specifying the repos? And what number is "too many repos" for you? You can specify sub-groups for Gitlab if you only want a limited number of repositories, but I'm not sure how you would scope it down with Gitlab. Maybe topics?

**Comment by jayvdb** [comment]
Diskspace isnt my concern.  The time to fetch them all, and then regularly update them all, that is my primary concern.  I cancelled the workspace update at about 3% because of this.

I would be happy enough manually editing workspace.yoml to be honest.  An `add github org/repo` CLI would be useful of course.  The same should work for gitlab of course, except that it gets a bit more tricky with gitlab which have extra levels.  IMO the toml records need to explicitly say when it is a repo record, as using the API to determine org vs repo URLs is inefficient.

The other way for specifying repos that I would use is an import mechanism, one URL per line, so it can include github and gitlab and others.  Then I can generate that input file using other tools.

**Comment by epcim** [comment]
Individual repos, filters. Even add repositories to "list" by local scan.
The tool even fetch and track all repos of users I follow :/

CC @orf

**Comment by rafi** [comment]
1. You could add a `dir` provider, e.g. `git workspace add dir /path/to/repo`
2. You can also allow specifying a path and recurse to discover ad-hoc repositories, e.g. `git workspace fetch .` (discover repos in current path), `git workspace fetch /path/to/projects` (discover projects in path)

**Comment by magiconair** [comment]
We have about 1500 repos and for security concerns I do not want to have them all on my laptop. However, I need repos which all start with a certain name, e.g. `'service-.*'` . 

I've tried `--exclude '^service-.*'` which didn't work. 

Adding an `--include` option which supports a regular expression and can be specified multiple times analogous to the `--exclude` option should do the trick.
