### ISSUE TITLE
Arbitrary projects

### ISSUE THREAD

**Issue by juanibiapina** [orf/git-workspace#24]
Do you have an idea on how to handle arbitrary projects? For instance, I need to clone this project now in order to work on it, and previously I would do just this:

```
dev start orf/git-workspace
```

This would take care of cloning the local repo in the correct location. I imagine this would fit into the concept of a git workspace.

**Comment by orf** [comment]
Hmm, so the idea for contributing to repositories you don't own is to just fork it, then a `git workspace update` will pull your clone (with the upstream set). You then work on that one and make a PR as usual.

However, for just cloning and experimenting without forking this isn't great. The problem is that the tool is tied to what is currently in Github or Gitlab, so unless `dev start ...` would create the project in github/gitlab then it would be archived at the next `git workspace update`.

I guess we could add a `scratch` repository that is excluded from archiving?

**Comment by juanibiapina** [comment]
I only used `dev` as an example. I was thinking more in terms of:

```
git workspace add github orf/git-workspace
```

Which would allow me to keep arbitrary repositories locally.

My purpose is to use git-workspace to manage all my repository cloning needs.

**Comment by juanibiapina** [comment]
What if we could specify single projects like this:

```
git workspace add github orf/git-workspace
```

We would need to detect that it's a single repo based on the presence of the slash. Or the command can also be changed to differentiate between single repos and organizations. Something like this for users or orgs:

```
git workspace add-user github orf
```

**Comment by orf** [comment]
I'm still not convinced that there is much value over just forking the project and using `git workspace update`. 

_However_, I don't think it would be very hard to implement this, so lets try it. We would have to create a new provider that stores all the information about a single `Repository`.

**Comment by juanibiapina** [comment]
Let me try to argue a bit.

It might be just me, but I browse code locally for a lot of repositories without having the intention to ever forking them. For that I currently use `hub`:

```
hub clone orf/git-workspace
```

And then in the rare case I need to fork:

```
hub fork
```

This is the kind of workflow I want to continue to have. I don't need to leave my terminal to do any of those things.

**Comment by orf** [comment]
Ok, yeah I see the value in this. I will have a think about the best implementation, and if it involves the lockfile at all.

The idea of skipping forks came up in #3, so it’s something I’d like to include.

Tom

**Comment by orf** [comment]
Skipping forks is done in #31

**Comment by juanibiapina** [comment]
I'm not using this project anymore so feel free to close this.
