### ISSUE TITLE
Archive, desire it's own command

### ISSUE THREAD

**Issue by epcim** [orf/git-workspace#243]
use-case: if you comment part of your workspace.yaml (on next update your repos are moved to .archive). 

(Note, I possibly hit this because I defined one record in workspace.yaml per my GH organization). So the `git workspace updpate` did actually have run multiple times on the same path.)

More rational is to 
- perform .archive old repos only when requested
- add option enable/diisable to source record in workspace.yaml to avoid processing (so you dont have to comment out it)

**Comment by epcim** [comment]
@orf  Is the project dead?

**Comment by orf** [comment]
Hey! It’s not dead, I’m just really busy right now :(

I like the idea of having a separate command, I think that’s a really good idea.

**Comment by jayvdb** [comment]
IMO a separate command is a great idea.

I suggest also expanding what it does to allow (i.e. user opt-in) aggressively cull the unnecessary parts of the directory. e.g. https://stackoverflow.com/questions/71962963/how-to-archive-a-git-repository-for-long-term-storage , ideally ending up with only a `.git`, listing any file which is in the directory that isnt in the .git.

Especially for Rust projects, deleting the `target` directory which can be *huge*, and users probably dont need it.

**Comment by orf** [comment]
I've implemented this - when running `update` it will tell you if there are any repositories that can be archived. There is a separate `archive` command that will prompt you before taking any actions.

I didn't want to delete anything within the archived repo itself as a safeguard against any bugs or data loss.
