### ISSUE TITLE
Mirrors and forks

### ISSUE THREAD

**Issue by pawamoy** [orf/git-workspace#25]
Hi, very nice project 🙂 !

It fits my workflow perfectly!

...except for a few things :smile: :
- I like to keep my local forks into a "forks" directory instead of my "pawamoy" directory inside the workspace, because it helps distinguish them from my own projects. Would you be willing to implement an option to move forks in a custom directory?
- I always have two online copies of my repos: one on GitHub and one on GitLab. I have the same username on both (pawamoy), and the projects also have the same name (I also have same orgs with different names, but lets see that later). My local clones are configured to push on both remotes. Would you be willing to add a feature that allows users to do that when cloning projects? Something like telling `git-workspace` to clone from GitHub but also set remote urls and push urls for both GitHub and another remote like GitLab?

**Comment by orf** [comment]
Hey! Thank you for the kind words.

> I like to keep my local forks into a "forks" directory instead of my "pawamoy" directory inside the workspace, because it helps distinguish them from my own projects. Would you be willing to implement an option to move forks in a custom directory?

I would be willing to add this to the tool, but it would have to have a nice way of specifying this. I think perhaps the tool can have an option while adding a provider to say `no forks` or `only forks`, so you can add two providers with different directories, one for forks and one without forks?

> I always have two online copies of my repos: one on GitHub and one on GitLab.

**Comment by pawamoy** [comment]
Actually I just realized the projets are cloned in "provider" directories (`github/pawamoy/foo`) which is not how I organize my repos locally 😅 

Just to be clear, here's how I do it:
```
workspace/
├── pawamoy/
│   ├── foo/
│   └── bar/
├── forks/
│   ├── fork/
│   └── bork/
└── my-org/
    ├── orga/
    └── orgo/
```

...so git-workspace might not be for me.

I'll let you choose whether to close this issue or do something about it 🙂

**Comment by orf** [comment]
Skipping forks is done in #31
