### ISSUE TITLE
Show error message

### ISSUE THREAD

**Issue by jayvdb** [orf/git-workspace#283]
I had a token which wasnt authorised for a certain org, and this tool gave only the error:

> thread '<unnamed>' panicked at 'Invalid response from GitHub for user [org-name]', src/providers/github.rs:138:36

Underneath the error, the actual response is more helpful:

```json
{"data":{"repositoryOwner":null},"errors":[{"extensions":{"saml_failure":true},"locations":[{"column":9,"line":4}],"message":"Resource protected by organization SAML enforcement. You must grant your Personal Access token access to this organization.","path":["repositoryOwner","repositories"],"type":"FORBIDDEN"}]}
```

It would be nice if this error could be shown.

**Comment by orf** [comment]
Thanks for the suggestion! Closed by 7e31bcb0919cc2346a60285cc04c8eb90810404e
