### ISSUE TITLE
[question] naming

### ISSUE THREAD

**Issue by kcris** [orf/git-workspace#295]
Hi,

@orf 

I guess this one has nothing to do with the [git worktree](https://git-scm.com/docs/git-worktree) official command, right?
(that one handles multiple copies of the *same* repo, locally)

Whereas your `git-workspace` handles multiple, independent repositories, at once
It seems to do the same job as [myrepos](https://myrepos.branchable.com)

**Comment by orf** [comment]
Nope, that's a different command.

I have not heard of myrepos before, thanks for linking. I'd say it's a bit different, but in the same area.
