### ISSUE TITLE
Running update with wrong workspace archived everything in that directory

### ISSUE THREAD

**Issue by jayvdb** [orf/git-workspace#297]
I ran `~/git-workspaces/github> git-workspace --workspace . update` , i.e. inside the `github` sub-directory instead of in `~/git-workspaces`.  There is no `workspace.toml` in this `github` sub-directory, and git-workspace then "archived" the entire tree under that subdirectory, and created an "empty" `workspace-lock.toml`, i.e. `repo = []`.

The output doesnt mention the `.archive` directory, so naturally I panicked initially.

Easily fixed after finding the `.archive` directory.

However, IMO there should be some check, probably for existence of `workspace.toml`.

**Comment by orf** [comment]
Oh dear! Sorry about that @jayvdb. I can reproduce it and I'll fix that - it was supposed to guard against that, but I guess that it is broken.
