### ISSUE TITLE
Archive fails if there is an "identical" existing archive

### ISSUE THREAD

**Issue by jayvdb** [orf/git-workspace#317]
I dont know how I ended up with a new checkout of the archived repo, but when it tries to archive it, it fails because there is already one.

The new clone is clean, while the archived one does have some extra local branches, but everything in the new clone is in the archived one.

```
...
Archiving 1 repositories
Archiving github/org/repo
Error: Error archiving repositories

Caused by:
    0: Error moving directory /home/jayvdb/git-workspaces/github/org/repo to /home/jayvdb/git-workspaces/.archive/github/org/repo
    1: Directory not empty (os error 39)
```

**Comment by orf** [comment]
This is fixed by 91e0df49c097d50689c4bd2106d9dcd67f50d96d - the archive command will report better errors and continue where it can.
