### ISSUE TITLE
Feature: Allow filtering repos by recent activity

### ISSUE THREAD

**Issue by Dietr1ch** [orf/git-workspace#373]
It'd be neat to get all the repos with activity within a configured time horizon.
Otherwise I'll just download repos that I don't care that much about anymore (should I instead just archive them?)

**Comment by orf** [comment]
I'm going to close this - i appreciate the feature request, but the point of the tool is to download/mirror everything.

You can skip forks or include/exclude repositories by regular expressions if you need to filter out some subset of repositories, but a recency metric isn't something I'd like to add.
